service: word-guess-server

frameworkVersion: '4'

plugins:
  - serverless-offline
  # Note: serverless-plugin-typescript is not included as it's not compatible with serverless v4+

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm
  build:
    esbuild: false

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 2560
  timeout: 29
  logRetentionInDays: 14
  environment:
    NODE_ENV: ${self:provider.stage}
    WORD_GUESS_DB_TABLE_NAME: ${env:WORD_GUESS_DB_TABLE_NAME, 'word-guess-db'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY} # Add this line
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  hello:
    handler: src/handlers/app.handler
    events:
      - http:
          method: POST
          path: app
          cors: true

package:
  individually: true
